//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnaFoo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suggestion
    {
        public int Id { get; set; }
        public int SnackId { get; set; }
        public System.DateTime SuggestedOn { get; set; }
    }
}
